export const AppRoute = {
  auth: {
    login: '/login',
    signup: '/signup',
    onboarding: '/onboarding',
    resetPassword: '/reset-password',
  },
  parent: {
    dashboard: '/(parent)/(tabs)/dashboard',
    profile: '/(parent)/(tabs)/profile',
    students: '/(parent)/students',
    linkStudent: '/(parent)/students/link',
    studentDetails: (id: string) => `/(parent)/students/${id}` as const,
    studentAttendance: (id: string) => `/(parent)/students/${id}/attendance` as const,
    studentPerformance: (id: string) => `/(parent)/students/${id}/performance` as const,
    notifications: '/(parent)/notifications',
  },
  teacher: {
    dashboard: '/(teacher)/(tabs)/dashboard',
    students: '/(teacher)/(tabs)/students',
    sessions: '/(teacher)/(tabs)/sessions',
    profile: '/(teacher)/(tabs)/profile',
    studentCreate: '/(teacher)/students/create',
    studentEdit: (id: string) => `/(teacher)/students/${id}/edit` as const,
    connectionCode: (id: string) => `/(teacher)/students/${id}/connection-code` as const,
    sessionCreate: '/(teacher)/sessions/create',
    sessionEdit: (id: string) => `/(teacher)/sessions/${id}/edit` as const,
    attendance: (instanceId: string) => `/(teacher)/attendance/${instanceId}` as const,
    sessionRankings: (templateId: string) => `/(teacher)/sessions/${templateId}/rankings` as const,
    studentPerformance: (studentId: string) => `/(teacher)/students/${studentId}/performance` as const,
  },
  manager: {
    setup: '/(manager)/setup',
    dashboard: '/(manager)/(tabs)/dashboard',
    students: '/(manager)/(tabs)/students',
    sessions: '/(manager)/(tabs)/sessions',
    teachers: '/(manager)/(tabs)/teachers',
    more: '/(manager)/(tabs)/more',
    studentCreate: '/(manager)/students/create',
    studentDetail: (id: string) => `/(manager)/students/${id}` as const,
    sessionCreate: '/(manager)/sessions/create',
    sessionDetail: (id: string) => `/(manager)/sessions/${id}` as const,
    attendance: (instanceId: string) => `/(manager)/sessions/attendance/${instanceId}` as const,
    teacherInvite: '/(manager)/teachers/invite',
    settings: '/(manager)/settings',
    reports: '/(manager)/reports',
  },
  admin: {
    dashboard: '/(admin)/dashboard',
    teachers: '/(admin)/teachers',
    parents: '/(admin)/parents',
  },
  superAdmin: {
    dashboard: '/(super-admin)/dashboard',
    plans: '/(super-admin)/plans',
    admins: '/(super-admin)/admins',
  },
} as const;
